---
dist: trusty
language: python
python: "2.7"

# Use isolated build instance
sudo: required

# Handle git submodules yourself
git:
  submodules: false

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
  matrix:
    - RUN="shellcheck yamlcheck syntax full"
    #- RUN="yamlcheck"
    #- RUN="syntax"
    #- RUN="ci"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install ansible==2.4.0.0
  - pip install urllib3 yamllint
  - ansible --version

script:
  - ./tests/tests.sh
