---
- name: test letsencrypt role
  hosts: domain-host
  gather_facts: yes
  remote_user: "{{ default_user }}"
  become: true
  vars:
    backports_uri: http://ftp.debian.org/debian
    domain: "{{ inventory_hostname }}"
  tasks:
    - debug: msg="ansible_memtotal_mb={{ ansible_memtotal_mb }}, ansible_swaptotal_mb={{ ansible_swaptotal_mb }}"
    - include_role:
        name: swapfile
      become: true
