---
- name: test letsencrypt role
  hosts: domain-host
  gather_facts: yes
  become: yes
  vars:
    backports_uri: http://ftp.debian.org/debian
    domain: "{{ inventory_hostname }}"
  tasks:
    - debug: msg="ansible_memtotal_mb={{ ansible_memtotal_mb }}, ansible_swaptotal_mb={{ ansible_swaptotal_mb }}"
  roles:
    #- letsencrypt
    - wpcli
