---
- name: generate ssh keys using raw command module # will not override an existing key
  become: true
  command: ssh-keygen -o -a 100 -t ed25519 -f /root/.ssh/id_ed25519 -q -N ""
  args:
    creates: /root/.ssh/id_ed25519

- name: capture output of id command
  become: true
  command: cat /root/.ssh/id_ed25519.pub
  register: pubkey
  check_mode: no

# @TODO Hardcoded
- name: upload the newly created public key to Bitbucket
  uri:
    url: https://api.bitbucket.org/1.0/users/{{ git_provider_accountname }}/ssh-keys
    method: POST
    user: "{{ git_provider_user }}"
    password: "{{ git_provider_passwd }}"
    body: "label=root@{{ fqdn }}&key={{ pubkey.stdout|urlencode}}"
    force_basic_auth: yes
  register: result
  failed_when: result.status != 200 and "Someone has already registered that SSH key" not in result.content

- name: start the wordpress installation process
  import_tasks: git.yml

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
