---
- name: Create database for each site if not present
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_host: "{{ wp_db_host }}"
    login_user: "{{ wp_db_root }}"
    login_password: "{{ wp_db_root_pwd }}"

- name: Create/assign database user to db and grant permissions
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    login_host: "{{ wp_db_host }}"
    login_user: "{{ wp_db_root }}"
    login_password: "{{ wp_db_root_pwd }}"
