---
- name: config git with name and email
  shell: |
    git config user.name "{{ git_provider_accountname }}"
    git config user.email {{ git_provider_user }}
    git config core.filemode false
    git branch --set-upstream-to=origin/master master
  args:
    chdir: "{{ wp_install_dir }}"

- name: apply owner and permission
  block:
    - file:
        path: "{{ wp_install_dir }}"
        owner: www-data
        group: www-data
        mode: 0755
        recurse: yes
      # apply specific owner and permission for db_backup
    - file:
        path: "{{ wp_install_dir }}/db_backup"
        owner: root
        group: root
        mode: 0770
      # apply specific owner and permission for db_backup/database.sql
    - file:
        path: "{{ wp_install_dir }}/db_backup/{{ wp_db_name }}.sql"
        owner: root
        group: root
        mode: 0660

- name: Wordpress | Import saved database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: import
    target: "{{ wp_install_dir }}/db_backup/{{ wp_db_name }}.sql"
    login_host: "{{ wp_db_host }}"
    login_user: "{{ wp_db_root }}"
    login_password: "{{ wp_db_root_pwd }}"

- name: wp cli search-replace old domain with {{ fqdn }}
  become: yes
  become_user: www-data
  command: wp search-replace {{ old-domain }} {{ fqdn }}
  args:
    chdir: "{{ wp_install_dir }}"
  when: old_domain is defined
