---
- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"

- name: remove packages
  shell: >
    apt purge --auto-remove snapd ubuntu-core-launcher squashfs-tools lxd-client lxcfs -y

- name: Perform a full system upgrade
  apt:
    upgrade: "safe"

- name: change the default editor to vim.nox
  shell: >
    update-alternatives --set editor /usr/bin/vim.nox

- name: Copy the unattended-upgrades templates to enable automatic security updates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "20auto-upgrades",       dest: "/etc/apt/apt.conf.d" }
    - { src: "50unattended-upgrades", dest: "/etc/apt/apt.conf.d" }
