---
- name: Check if wp command is installed
  shell: wp --version
  register: wp_check
  ignore_errors: True
  become: False
  changed_when: False

- name: install wpcli
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755
  when: wp_check.rc == 2

- name: update wp if already installed
  expect:
    command: wp cli update
    responses:
      (?i)[y/n]: y
    timeout: 3
  register: result
  changed_when: '"WP-CLI is at the latest version" not in result.stdout'
  ignore_errors: True

- name: update the domain name if the var wp_old_domain exist
  shell: sudo -uwww-data wp search-replace {{ wp_old_domain }} {{ domain }}
  args:
    chdir: "{{ wp_install_dir }}"
  when: wp_old_domain is defined
  become: False